// Auto-generated by enum_mapper_generator.py
// DO NOT EDIT THIS FILE MANUALLY

#pragma once
#include <string>
#include <unordered_map>
#include <stdexcept>

class PacketNumberMapper {
public:
    // 메시지 타입명에서 protocol number 추출
    // 예: "C2S_TestEcho" → 1
    static unsigned short GetProtocolNumber(const std::string& message_type_name) {
        // "_" 뒤의 packet_number 이름 추출
        size_t pos = message_type_name.find('_');
        if (pos == std::string::npos) {
            throw std::invalid_argument("Invalid message type name: " + message_type_name);
        }
        
        std::string packet_name = message_type_name.substr(pos + 1);
        
        static const std::unordered_map<std::string, unsigned short> name_to_number = {
            {"TestEcho", 1},
            {"AccountRegister", 2},
            {"AccountLogin", 3},
        };
        
        auto it = name_to_number.find(packet_name);
        if (it != name_to_number.end()) {
            return it->second;
        }
        throw std::invalid_argument("Unknown packet name: " + packet_name);
    }
    
    // protocol number → 이름
    static const char* GetPacketName(unsigned short protocol_number) {
        static const std::unordered_map<unsigned short, const char*> number_to_name = {
            {1, "TestEcho"},
            {2, "AccountRegister"},
            {3, "AccountLogin"},
        };
        
        auto it = number_to_name.find(protocol_number);
        if (it != number_to_name.end()) {
            return it->second;
        }
        return "UNKNOWN";
    }
};
