// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Protocols_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Protocols_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Protocols_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocols_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Protocols_2eproto;
class C2S_TestEcho;
struct C2S_TestEchoDefaultTypeInternal;
extern C2S_TestEchoDefaultTypeInternal _C2S_TestEcho_default_instance_;
class S2C_TestEcho;
struct S2C_TestEchoDefaultTypeInternal;
extern S2C_TestEchoDefaultTypeInternal _S2C_TestEcho_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::C2S_TestEcho* Arena::CreateMaybeMessage<::C2S_TestEcho>(Arena*);
template<> ::S2C_TestEcho* Arena::CreateMaybeMessage<::S2C_TestEcho>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum packet_number : int {
  NONE = 0,
  TestEcho = 1,
  packet_number_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  packet_number_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool packet_number_IsValid(int value);
constexpr packet_number packet_number_MIN = NONE;
constexpr packet_number packet_number_MAX = TestEcho;
constexpr int packet_number_ARRAYSIZE = packet_number_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* packet_number_descriptor();
template<typename T>
inline const std::string& packet_number_Name(T enum_t_value) {
  static_assert(::std::is_same<T, packet_number>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function packet_number_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    packet_number_descriptor(), enum_t_value);
}
inline bool packet_number_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, packet_number* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<packet_number>(
    packet_number_descriptor(), name, value);
}
// ===================================================================

class C2S_TestEcho final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:C2S_TestEcho) */ {
 public:
  inline C2S_TestEcho() : C2S_TestEcho(nullptr) {}
  ~C2S_TestEcho() override;
  explicit PROTOBUF_CONSTEXPR C2S_TestEcho(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2S_TestEcho(const C2S_TestEcho& from);
  C2S_TestEcho(C2S_TestEcho&& from) noexcept
    : C2S_TestEcho() {
    *this = ::std::move(from);
  }

  inline C2S_TestEcho& operator=(const C2S_TestEcho& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2S_TestEcho& operator=(C2S_TestEcho&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2S_TestEcho& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2S_TestEcho* internal_default_instance() {
    return reinterpret_cast<const C2S_TestEcho*>(
               &_C2S_TestEcho_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C2S_TestEcho& a, C2S_TestEcho& b) {
    a.Swap(&b);
  }
  inline void Swap(C2S_TestEcho* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2S_TestEcho* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2S_TestEcho* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2S_TestEcho>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2S_TestEcho& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2S_TestEcho& from) {
    C2S_TestEcho::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2S_TestEcho* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "C2S_TestEcho";
  }
  protected:
  explicit C2S_TestEcho(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRandNumberFieldNumber = 1,
  };
  // int32 rand_number = 1;
  void clear_rand_number();
  int32_t rand_number() const;
  void set_rand_number(int32_t value);
  private:
  int32_t _internal_rand_number() const;
  void _internal_set_rand_number(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:C2S_TestEcho)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t rand_number_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocols_2eproto;
};
// -------------------------------------------------------------------

class S2C_TestEcho final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:S2C_TestEcho) */ {
 public:
  inline S2C_TestEcho() : S2C_TestEcho(nullptr) {}
  ~S2C_TestEcho() override;
  explicit PROTOBUF_CONSTEXPR S2C_TestEcho(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2C_TestEcho(const S2C_TestEcho& from);
  S2C_TestEcho(S2C_TestEcho&& from) noexcept
    : S2C_TestEcho() {
    *this = ::std::move(from);
  }

  inline S2C_TestEcho& operator=(const S2C_TestEcho& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2C_TestEcho& operator=(S2C_TestEcho&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2C_TestEcho& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2C_TestEcho* internal_default_instance() {
    return reinterpret_cast<const S2C_TestEcho*>(
               &_S2C_TestEcho_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S2C_TestEcho& a, S2C_TestEcho& b) {
    a.Swap(&b);
  }
  inline void Swap(S2C_TestEcho* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2C_TestEcho* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2C_TestEcho* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2C_TestEcho>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2C_TestEcho& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2C_TestEcho& from) {
    S2C_TestEcho::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2C_TestEcho* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "S2C_TestEcho";
  }
  protected:
  explicit S2C_TestEcho(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSessionIdFieldNumber = 1,
    kRandNumberFieldNumber = 2,
  };
  // int32 session_id = 1;
  void clear_session_id();
  int32_t session_id() const;
  void set_session_id(int32_t value);
  private:
  int32_t _internal_session_id() const;
  void _internal_set_session_id(int32_t value);
  public:

  // int32 rand_number = 2;
  void clear_rand_number();
  int32_t rand_number() const;
  void set_rand_number(int32_t value);
  private:
  int32_t _internal_rand_number() const;
  void _internal_set_rand_number(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:S2C_TestEcho)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t session_id_;
    int32_t rand_number_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocols_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C2S_TestEcho

// int32 rand_number = 1;
inline void C2S_TestEcho::clear_rand_number() {
  _impl_.rand_number_ = 0;
}
inline int32_t C2S_TestEcho::_internal_rand_number() const {
  return _impl_.rand_number_;
}
inline int32_t C2S_TestEcho::rand_number() const {
  // @@protoc_insertion_point(field_get:C2S_TestEcho.rand_number)
  return _internal_rand_number();
}
inline void C2S_TestEcho::_internal_set_rand_number(int32_t value) {
  
  _impl_.rand_number_ = value;
}
inline void C2S_TestEcho::set_rand_number(int32_t value) {
  _internal_set_rand_number(value);
  // @@protoc_insertion_point(field_set:C2S_TestEcho.rand_number)
}

// -------------------------------------------------------------------

// S2C_TestEcho

// int32 session_id = 1;
inline void S2C_TestEcho::clear_session_id() {
  _impl_.session_id_ = 0;
}
inline int32_t S2C_TestEcho::_internal_session_id() const {
  return _impl_.session_id_;
}
inline int32_t S2C_TestEcho::session_id() const {
  // @@protoc_insertion_point(field_get:S2C_TestEcho.session_id)
  return _internal_session_id();
}
inline void S2C_TestEcho::_internal_set_session_id(int32_t value) {
  
  _impl_.session_id_ = value;
}
inline void S2C_TestEcho::set_session_id(int32_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:S2C_TestEcho.session_id)
}

// int32 rand_number = 2;
inline void S2C_TestEcho::clear_rand_number() {
  _impl_.rand_number_ = 0;
}
inline int32_t S2C_TestEcho::_internal_rand_number() const {
  return _impl_.rand_number_;
}
inline int32_t S2C_TestEcho::rand_number() const {
  // @@protoc_insertion_point(field_get:S2C_TestEcho.rand_number)
  return _internal_rand_number();
}
inline void S2C_TestEcho::_internal_set_rand_number(int32_t value) {
  
  _impl_.rand_number_ = value;
}
inline void S2C_TestEcho::set_rand_number(int32_t value) {
  _internal_set_rand_number(value);
  // @@protoc_insertion_point(field_set:S2C_TestEcho.rand_number)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::packet_number> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::packet_number>() {
  return ::packet_number_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Protocols_2eproto
