// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

#include "Protocols.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR C2S_TestEcho::C2S_TestEcho(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.rand_number_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C2S_TestEchoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_TestEchoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_TestEchoDefaultTypeInternal() {}
  union {
    C2S_TestEcho _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_TestEchoDefaultTypeInternal _C2S_TestEcho_default_instance_;
PROTOBUF_CONSTEXPR S2C_TestEcho::S2C_TestEcho(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.session_id_)*/0
  , /*decltype(_impl_.rand_number_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S2C_TestEchoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_TestEchoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_TestEchoDefaultTypeInternal() {}
  union {
    S2C_TestEcho _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_TestEchoDefaultTypeInternal _S2C_TestEcho_default_instance_;
static ::_pb::Metadata file_level_metadata_Protocols_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Protocols_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Protocols_2eproto = nullptr;

const uint32_t TableStruct_Protocols_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::C2S_TestEcho, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::C2S_TestEcho, _impl_.rand_number_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::S2C_TestEcho, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::S2C_TestEcho, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::S2C_TestEcho, _impl_.rand_number_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::C2S_TestEcho)},
  { 7, -1, -1, sizeof(::S2C_TestEcho)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_C2S_TestEcho_default_instance_._instance,
  &::_S2C_TestEcho_default_instance_._instance,
};

const char descriptor_table_protodef_Protocols_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017Protocols.proto\"#\n\014C2S_TestEcho\022\023\n\013ran"
  "d_number\030\001 \001(\005\"7\n\014S2C_TestEcho\022\022\n\nsessio"
  "n_id\030\001 \001(\005\022\023\n\013rand_number\030\002 \001(\005*\'\n\rpacke"
  "t_number\022\010\n\004NONE\020\000\022\014\n\010TestEcho\020\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_Protocols_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Protocols_2eproto = {
    false, false, 160, descriptor_table_protodef_Protocols_2eproto,
    "Protocols.proto",
    &descriptor_table_Protocols_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_Protocols_2eproto::offsets,
    file_level_metadata_Protocols_2eproto, file_level_enum_descriptors_Protocols_2eproto,
    file_level_service_descriptors_Protocols_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Protocols_2eproto_getter() {
  return &descriptor_table_Protocols_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Protocols_2eproto(&descriptor_table_Protocols_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* packet_number_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Protocols_2eproto);
  return file_level_enum_descriptors_Protocols_2eproto[0];
}
bool packet_number_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class C2S_TestEcho::_Internal {
 public:
};

C2S_TestEcho::C2S_TestEcho(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:C2S_TestEcho)
}
C2S_TestEcho::C2S_TestEcho(const C2S_TestEcho& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C2S_TestEcho* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.rand_number_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.rand_number_ = from._impl_.rand_number_;
  // @@protoc_insertion_point(copy_constructor:C2S_TestEcho)
}

inline void C2S_TestEcho::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.rand_number_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

C2S_TestEcho::~C2S_TestEcho() {
  // @@protoc_insertion_point(destructor:C2S_TestEcho)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C2S_TestEcho::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void C2S_TestEcho::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C2S_TestEcho::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_TestEcho)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.rand_number_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C2S_TestEcho::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 rand_number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.rand_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C2S_TestEcho::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:C2S_TestEcho)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 rand_number = 1;
  if (this->_internal_rand_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_rand_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:C2S_TestEcho)
  return target;
}

size_t C2S_TestEcho::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:C2S_TestEcho)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 rand_number = 1;
  if (this->_internal_rand_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rand_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C2S_TestEcho::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C2S_TestEcho::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C2S_TestEcho::GetClassData() const { return &_class_data_; }


void C2S_TestEcho::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C2S_TestEcho*>(&to_msg);
  auto& from = static_cast<const C2S_TestEcho&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:C2S_TestEcho)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_rand_number() != 0) {
    _this->_internal_set_rand_number(from._internal_rand_number());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C2S_TestEcho::CopyFrom(const C2S_TestEcho& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:C2S_TestEcho)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C2S_TestEcho::IsInitialized() const {
  return true;
}

void C2S_TestEcho::InternalSwap(C2S_TestEcho* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.rand_number_, other->_impl_.rand_number_);
}

::PROTOBUF_NAMESPACE_ID::Metadata C2S_TestEcho::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocols_2eproto_getter, &descriptor_table_Protocols_2eproto_once,
      file_level_metadata_Protocols_2eproto[0]);
}

// ===================================================================

class S2C_TestEcho::_Internal {
 public:
};

S2C_TestEcho::S2C_TestEcho(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:S2C_TestEcho)
}
S2C_TestEcho::S2C_TestEcho(const S2C_TestEcho& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S2C_TestEcho* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){}
    , decltype(_impl_.rand_number_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.session_id_, &from._impl_.session_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.rand_number_) -
    reinterpret_cast<char*>(&_impl_.session_id_)) + sizeof(_impl_.rand_number_));
  // @@protoc_insertion_point(copy_constructor:S2C_TestEcho)
}

inline void S2C_TestEcho::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.session_id_){0}
    , decltype(_impl_.rand_number_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S2C_TestEcho::~S2C_TestEcho() {
  // @@protoc_insertion_point(destructor:S2C_TestEcho)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S2C_TestEcho::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void S2C_TestEcho::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S2C_TestEcho::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_TestEcho)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.rand_number_) -
      reinterpret_cast<char*>(&_impl_.session_id_)) + sizeof(_impl_.rand_number_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S2C_TestEcho::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 rand_number = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.rand_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S2C_TestEcho::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:S2C_TestEcho)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 session_id = 1;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_session_id(), target);
  }

  // int32 rand_number = 2;
  if (this->_internal_rand_number() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_rand_number(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:S2C_TestEcho)
  return target;
}

size_t S2C_TestEcho::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:S2C_TestEcho)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 session_id = 1;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_session_id());
  }

  // int32 rand_number = 2;
  if (this->_internal_rand_number() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_rand_number());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S2C_TestEcho::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S2C_TestEcho::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S2C_TestEcho::GetClassData() const { return &_class_data_; }


void S2C_TestEcho::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S2C_TestEcho*>(&to_msg);
  auto& from = static_cast<const S2C_TestEcho&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_TestEcho)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_session_id() != 0) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_rand_number() != 0) {
    _this->_internal_set_rand_number(from._internal_rand_number());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S2C_TestEcho::CopyFrom(const S2C_TestEcho& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_TestEcho)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2C_TestEcho::IsInitialized() const {
  return true;
}

void S2C_TestEcho::InternalSwap(S2C_TestEcho* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S2C_TestEcho, _impl_.rand_number_)
      + sizeof(S2C_TestEcho::_impl_.rand_number_)
      - PROTOBUF_FIELD_OFFSET(S2C_TestEcho, _impl_.session_id_)>(
          reinterpret_cast<char*>(&_impl_.session_id_),
          reinterpret_cast<char*>(&other->_impl_.session_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S2C_TestEcho::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Protocols_2eproto_getter, &descriptor_table_Protocols_2eproto_once,
      file_level_metadata_Protocols_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::C2S_TestEcho*
Arena::CreateMaybeMessage< ::C2S_TestEcho >(Arena* arena) {
  return Arena::CreateMessageInternal< ::C2S_TestEcho >(arena);
}
template<> PROTOBUF_NOINLINE ::S2C_TestEcho*
Arena::CreateMaybeMessage< ::S2C_TestEcho >(Arena* arena) {
  return Arena::CreateMessageInternal< ::S2C_TestEcho >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
