// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Protocols.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* C2S_REQ_Chat_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2S_REQ_Chat_reflection_ = NULL;
const ::google::protobuf::Descriptor* C2S_REQ_LOGIN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  C2S_REQ_LOGIN_reflection_ = NULL;
const ::google::protobuf::Descriptor* S2C_RES_LOGIN_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2C_RES_LOGIN_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* packet_number_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_Protocols_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_Protocols_2eproto() {
  protobuf_AddDesc_Protocols_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "Protocols.proto");
  GOOGLE_CHECK(file != NULL);
  C2S_REQ_Chat_descriptor_ = file->message_type(0);
  static const int C2S_REQ_Chat_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2S_REQ_Chat, sender_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2S_REQ_Chat, message_),
  };
  C2S_REQ_Chat_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      C2S_REQ_Chat_descriptor_,
      C2S_REQ_Chat::internal_default_instance(),
      C2S_REQ_Chat_offsets_,
      -1,
      -1,
      -1,
      sizeof(C2S_REQ_Chat),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2S_REQ_Chat, _internal_metadata_));
  C2S_REQ_LOGIN_descriptor_ = file->message_type(1);
  static const int C2S_REQ_LOGIN_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2S_REQ_LOGIN, nickname_),
  };
  C2S_REQ_LOGIN_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      C2S_REQ_LOGIN_descriptor_,
      C2S_REQ_LOGIN::internal_default_instance(),
      C2S_REQ_LOGIN_offsets_,
      -1,
      -1,
      -1,
      sizeof(C2S_REQ_LOGIN),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(C2S_REQ_LOGIN, _internal_metadata_));
  S2C_RES_LOGIN_descriptor_ = file->message_type(2);
  static const int S2C_RES_LOGIN_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2C_RES_LOGIN, is_mine_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2C_RES_LOGIN, nickname_),
  };
  S2C_RES_LOGIN_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      S2C_RES_LOGIN_descriptor_,
      S2C_RES_LOGIN::internal_default_instance(),
      S2C_RES_LOGIN_offsets_,
      -1,
      -1,
      -1,
      sizeof(S2C_RES_LOGIN),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2C_RES_LOGIN, _internal_metadata_));
  packet_number_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_Protocols_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      C2S_REQ_Chat_descriptor_, C2S_REQ_Chat::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      C2S_REQ_LOGIN_descriptor_, C2S_REQ_LOGIN::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      S2C_RES_LOGIN_descriptor_, S2C_RES_LOGIN::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_Protocols_2eproto() {
  C2S_REQ_Chat_default_instance_.Shutdown();
  delete C2S_REQ_Chat_reflection_;
  C2S_REQ_LOGIN_default_instance_.Shutdown();
  delete C2S_REQ_LOGIN_reflection_;
  S2C_RES_LOGIN_default_instance_.Shutdown();
  delete S2C_RES_LOGIN_reflection_;
}

void protobuf_InitDefaults_Protocols_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  C2S_REQ_Chat_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  C2S_REQ_LOGIN_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  S2C_RES_LOGIN_default_instance_.DefaultConstruct();
  C2S_REQ_Chat_default_instance_.get_mutable()->InitAsDefaultInstance();
  C2S_REQ_LOGIN_default_instance_.get_mutable()->InitAsDefaultInstance();
  S2C_RES_LOGIN_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_Protocols_2eproto_once_);
void protobuf_InitDefaults_Protocols_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_Protocols_2eproto_once_,
                 &protobuf_InitDefaults_Protocols_2eproto_impl);
}
void protobuf_AddDesc_Protocols_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_Protocols_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017Protocols.proto\"2\n\014C2S_REQ_Chat\022\021\n\tsen"
    "der_id\030\001 \001(\005\022\017\n\007message\030\003 \001(\t\"!\n\rC2S_REQ"
    "_LOGIN\022\020\n\010nickname\030\001 \001(\t\"2\n\rS2C_RES_LOGI"
    "N\022\017\n\007is_mine\030\001 \001(\010\022\020\n\010nickname\030\002 \001(\t*\031\n\r"
    "packet_number\022\010\n\004NONE\020\000b\006proto3", 191);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Protocols.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_Protocols_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_Protocols_2eproto_once_);
void protobuf_AddDesc_Protocols_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_Protocols_2eproto_once_,
                 &protobuf_AddDesc_Protocols_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_Protocols_2eproto {
  StaticDescriptorInitializer_Protocols_2eproto() {
    protobuf_AddDesc_Protocols_2eproto();
  }
} static_descriptor_initializer_Protocols_2eproto_;
const ::google::protobuf::EnumDescriptor* packet_number_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return packet_number_descriptor_;
}
bool packet_number_IsValid(int value) {
  switch (value) {
    case 0:
      return true;
    default:
      return false;
  }
}


namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int C2S_REQ_Chat::kSenderIdFieldNumber;
const int C2S_REQ_Chat::kMessageFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

C2S_REQ_Chat::C2S_REQ_Chat()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Protocols_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:C2S_REQ_Chat)
}

void C2S_REQ_Chat::InitAsDefaultInstance() {
}

C2S_REQ_Chat::C2S_REQ_Chat(const C2S_REQ_Chat& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:C2S_REQ_Chat)
}

void C2S_REQ_Chat::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_id_ = 0;
  _cached_size_ = 0;
}

C2S_REQ_Chat::~C2S_REQ_Chat() {
  // @@protoc_insertion_point(destructor:C2S_REQ_Chat)
  SharedDtor();
}

void C2S_REQ_Chat::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void C2S_REQ_Chat::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2S_REQ_Chat::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2S_REQ_Chat_descriptor_;
}

const C2S_REQ_Chat& C2S_REQ_Chat::default_instance() {
  protobuf_InitDefaults_Protocols_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<C2S_REQ_Chat> C2S_REQ_Chat_default_instance_;

C2S_REQ_Chat* C2S_REQ_Chat::New(::google::protobuf::Arena* arena) const {
  C2S_REQ_Chat* n = new C2S_REQ_Chat;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void C2S_REQ_Chat::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_REQ_Chat)
  sender_id_ = 0;
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool C2S_REQ_Chat::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:C2S_REQ_Chat)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 sender_id = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &sender_id_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_message;
        break;
      }

      // optional string message = 3;
      case 3: {
        if (tag == 26) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "C2S_REQ_Chat.message"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:C2S_REQ_Chat)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:C2S_REQ_Chat)
  return false;
#undef DO_
}

void C2S_REQ_Chat::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:C2S_REQ_Chat)
  // optional int32 sender_id = 1;
  if (this->sender_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->sender_id(), output);
  }

  // optional string message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "C2S_REQ_Chat.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->message(), output);
  }

  // @@protoc_insertion_point(serialize_end:C2S_REQ_Chat)
}

::google::protobuf::uint8* C2S_REQ_Chat::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:C2S_REQ_Chat)
  // optional int32 sender_id = 1;
  if (this->sender_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->sender_id(), target);
  }

  // optional string message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "C2S_REQ_Chat.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->message(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:C2S_REQ_Chat)
  return target;
}

size_t C2S_REQ_Chat::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:C2S_REQ_Chat)
  size_t total_size = 0;

  // optional int32 sender_id = 1;
  if (this->sender_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->sender_id());
  }

  // optional string message = 3;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2S_REQ_Chat::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:C2S_REQ_Chat)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const C2S_REQ_Chat* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const C2S_REQ_Chat>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:C2S_REQ_Chat)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:C2S_REQ_Chat)
    UnsafeMergeFrom(*source);
  }
}

void C2S_REQ_Chat::MergeFrom(const C2S_REQ_Chat& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:C2S_REQ_Chat)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void C2S_REQ_Chat::UnsafeMergeFrom(const C2S_REQ_Chat& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.sender_id() != 0) {
    set_sender_id(from.sender_id());
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
}

void C2S_REQ_Chat::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:C2S_REQ_Chat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2S_REQ_Chat::CopyFrom(const C2S_REQ_Chat& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:C2S_REQ_Chat)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool C2S_REQ_Chat::IsInitialized() const {

  return true;
}

void C2S_REQ_Chat::Swap(C2S_REQ_Chat* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C2S_REQ_Chat::InternalSwap(C2S_REQ_Chat* other) {
  std::swap(sender_id_, other->sender_id_);
  message_.Swap(&other->message_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata C2S_REQ_Chat::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2S_REQ_Chat_descriptor_;
  metadata.reflection = C2S_REQ_Chat_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// C2S_REQ_Chat

// optional int32 sender_id = 1;
void C2S_REQ_Chat::clear_sender_id() {
  sender_id_ = 0;
}
::google::protobuf::int32 C2S_REQ_Chat::sender_id() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_Chat.sender_id)
  return sender_id_;
}
void C2S_REQ_Chat::set_sender_id(::google::protobuf::int32 value) {
  
  sender_id_ = value;
  // @@protoc_insertion_point(field_set:C2S_REQ_Chat.sender_id)
}

// optional string message = 3;
void C2S_REQ_Chat::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& C2S_REQ_Chat::message() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_Chat.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void C2S_REQ_Chat::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:C2S_REQ_Chat.message)
}
void C2S_REQ_Chat::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:C2S_REQ_Chat.message)
}
void C2S_REQ_Chat::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:C2S_REQ_Chat.message)
}
::std::string* C2S_REQ_Chat::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:C2S_REQ_Chat.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* C2S_REQ_Chat::release_message() {
  // @@protoc_insertion_point(field_release:C2S_REQ_Chat.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void C2S_REQ_Chat::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:C2S_REQ_Chat.message)
}

inline const C2S_REQ_Chat* C2S_REQ_Chat::internal_default_instance() {
  return &C2S_REQ_Chat_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int C2S_REQ_LOGIN::kNicknameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

C2S_REQ_LOGIN::C2S_REQ_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Protocols_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:C2S_REQ_LOGIN)
}

void C2S_REQ_LOGIN::InitAsDefaultInstance() {
}

C2S_REQ_LOGIN::C2S_REQ_LOGIN(const C2S_REQ_LOGIN& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:C2S_REQ_LOGIN)
}

void C2S_REQ_LOGIN::SharedCtor() {
  nickname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

C2S_REQ_LOGIN::~C2S_REQ_LOGIN() {
  // @@protoc_insertion_point(destructor:C2S_REQ_LOGIN)
  SharedDtor();
}

void C2S_REQ_LOGIN::SharedDtor() {
  nickname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void C2S_REQ_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* C2S_REQ_LOGIN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return C2S_REQ_LOGIN_descriptor_;
}

const C2S_REQ_LOGIN& C2S_REQ_LOGIN::default_instance() {
  protobuf_InitDefaults_Protocols_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<C2S_REQ_LOGIN> C2S_REQ_LOGIN_default_instance_;

C2S_REQ_LOGIN* C2S_REQ_LOGIN::New(::google::protobuf::Arena* arena) const {
  C2S_REQ_LOGIN* n = new C2S_REQ_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void C2S_REQ_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_REQ_LOGIN)
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool C2S_REQ_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:C2S_REQ_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string nickname = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nickname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nickname().data(), this->nickname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "C2S_REQ_LOGIN.nickname"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:C2S_REQ_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:C2S_REQ_LOGIN)
  return false;
#undef DO_
}

void C2S_REQ_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:C2S_REQ_LOGIN)
  // optional string nickname = 1;
  if (this->nickname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nickname().data(), this->nickname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "C2S_REQ_LOGIN.nickname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->nickname(), output);
  }

  // @@protoc_insertion_point(serialize_end:C2S_REQ_LOGIN)
}

::google::protobuf::uint8* C2S_REQ_LOGIN::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:C2S_REQ_LOGIN)
  // optional string nickname = 1;
  if (this->nickname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nickname().data(), this->nickname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "C2S_REQ_LOGIN.nickname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->nickname(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:C2S_REQ_LOGIN)
  return target;
}

size_t C2S_REQ_LOGIN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:C2S_REQ_LOGIN)
  size_t total_size = 0;

  // optional string nickname = 1;
  if (this->nickname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nickname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void C2S_REQ_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:C2S_REQ_LOGIN)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const C2S_REQ_LOGIN* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const C2S_REQ_LOGIN>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:C2S_REQ_LOGIN)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:C2S_REQ_LOGIN)
    UnsafeMergeFrom(*source);
  }
}

void C2S_REQ_LOGIN::MergeFrom(const C2S_REQ_LOGIN& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:C2S_REQ_LOGIN)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void C2S_REQ_LOGIN::UnsafeMergeFrom(const C2S_REQ_LOGIN& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.nickname().size() > 0) {

    nickname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nickname_);
  }
}

void C2S_REQ_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:C2S_REQ_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C2S_REQ_LOGIN::CopyFrom(const C2S_REQ_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:C2S_REQ_LOGIN)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool C2S_REQ_LOGIN::IsInitialized() const {

  return true;
}

void C2S_REQ_LOGIN::Swap(C2S_REQ_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void C2S_REQ_LOGIN::InternalSwap(C2S_REQ_LOGIN* other) {
  nickname_.Swap(&other->nickname_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata C2S_REQ_LOGIN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = C2S_REQ_LOGIN_descriptor_;
  metadata.reflection = C2S_REQ_LOGIN_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// C2S_REQ_LOGIN

// optional string nickname = 1;
void C2S_REQ_LOGIN::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& C2S_REQ_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_LOGIN.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void C2S_REQ_LOGIN::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:C2S_REQ_LOGIN.nickname)
}
void C2S_REQ_LOGIN::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:C2S_REQ_LOGIN.nickname)
}
void C2S_REQ_LOGIN::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:C2S_REQ_LOGIN.nickname)
}
::std::string* C2S_REQ_LOGIN::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:C2S_REQ_LOGIN.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* C2S_REQ_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:C2S_REQ_LOGIN.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void C2S_REQ_LOGIN::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:C2S_REQ_LOGIN.nickname)
}

inline const C2S_REQ_LOGIN* C2S_REQ_LOGIN::internal_default_instance() {
  return &C2S_REQ_LOGIN_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int S2C_RES_LOGIN::kIsMineFieldNumber;
const int S2C_RES_LOGIN::kNicknameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

S2C_RES_LOGIN::S2C_RES_LOGIN()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_Protocols_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:S2C_RES_LOGIN)
}

void S2C_RES_LOGIN::InitAsDefaultInstance() {
}

S2C_RES_LOGIN::S2C_RES_LOGIN(const S2C_RES_LOGIN& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:S2C_RES_LOGIN)
}

void S2C_RES_LOGIN::SharedCtor() {
  nickname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  is_mine_ = false;
  _cached_size_ = 0;
}

S2C_RES_LOGIN::~S2C_RES_LOGIN() {
  // @@protoc_insertion_point(destructor:S2C_RES_LOGIN)
  SharedDtor();
}

void S2C_RES_LOGIN::SharedDtor() {
  nickname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void S2C_RES_LOGIN::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2C_RES_LOGIN::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2C_RES_LOGIN_descriptor_;
}

const S2C_RES_LOGIN& S2C_RES_LOGIN::default_instance() {
  protobuf_InitDefaults_Protocols_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<S2C_RES_LOGIN> S2C_RES_LOGIN_default_instance_;

S2C_RES_LOGIN* S2C_RES_LOGIN::New(::google::protobuf::Arena* arena) const {
  S2C_RES_LOGIN* n = new S2C_RES_LOGIN;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void S2C_RES_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_RES_LOGIN)
  is_mine_ = false;
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool S2C_RES_LOGIN::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:S2C_RES_LOGIN)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bool is_mine = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_mine_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_nickname;
        break;
      }

      // optional string nickname = 2;
      case 2: {
        if (tag == 18) {
         parse_nickname:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nickname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nickname().data(), this->nickname().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "S2C_RES_LOGIN.nickname"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:S2C_RES_LOGIN)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:S2C_RES_LOGIN)
  return false;
#undef DO_
}

void S2C_RES_LOGIN::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:S2C_RES_LOGIN)
  // optional bool is_mine = 1;
  if (this->is_mine() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->is_mine(), output);
  }

  // optional string nickname = 2;
  if (this->nickname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nickname().data(), this->nickname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "S2C_RES_LOGIN.nickname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nickname(), output);
  }

  // @@protoc_insertion_point(serialize_end:S2C_RES_LOGIN)
}

::google::protobuf::uint8* S2C_RES_LOGIN::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:S2C_RES_LOGIN)
  // optional bool is_mine = 1;
  if (this->is_mine() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->is_mine(), target);
  }

  // optional string nickname = 2;
  if (this->nickname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nickname().data(), this->nickname().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "S2C_RES_LOGIN.nickname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nickname(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:S2C_RES_LOGIN)
  return target;
}

size_t S2C_RES_LOGIN::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:S2C_RES_LOGIN)
  size_t total_size = 0;

  // optional bool is_mine = 1;
  if (this->is_mine() != 0) {
    total_size += 1 + 1;
  }

  // optional string nickname = 2;
  if (this->nickname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nickname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2C_RES_LOGIN::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:S2C_RES_LOGIN)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const S2C_RES_LOGIN* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const S2C_RES_LOGIN>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:S2C_RES_LOGIN)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:S2C_RES_LOGIN)
    UnsafeMergeFrom(*source);
  }
}

void S2C_RES_LOGIN::MergeFrom(const S2C_RES_LOGIN& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:S2C_RES_LOGIN)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void S2C_RES_LOGIN::UnsafeMergeFrom(const S2C_RES_LOGIN& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.is_mine() != 0) {
    set_is_mine(from.is_mine());
  }
  if (from.nickname().size() > 0) {

    nickname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nickname_);
  }
}

void S2C_RES_LOGIN::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:S2C_RES_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2C_RES_LOGIN::CopyFrom(const S2C_RES_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:S2C_RES_LOGIN)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool S2C_RES_LOGIN::IsInitialized() const {

  return true;
}

void S2C_RES_LOGIN::Swap(S2C_RES_LOGIN* other) {
  if (other == this) return;
  InternalSwap(other);
}
void S2C_RES_LOGIN::InternalSwap(S2C_RES_LOGIN* other) {
  std::swap(is_mine_, other->is_mine_);
  nickname_.Swap(&other->nickname_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata S2C_RES_LOGIN::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2C_RES_LOGIN_descriptor_;
  metadata.reflection = S2C_RES_LOGIN_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// S2C_RES_LOGIN

// optional bool is_mine = 1;
void S2C_RES_LOGIN::clear_is_mine() {
  is_mine_ = false;
}
bool S2C_RES_LOGIN::is_mine() const {
  // @@protoc_insertion_point(field_get:S2C_RES_LOGIN.is_mine)
  return is_mine_;
}
void S2C_RES_LOGIN::set_is_mine(bool value) {
  
  is_mine_ = value;
  // @@protoc_insertion_point(field_set:S2C_RES_LOGIN.is_mine)
}

// optional string nickname = 2;
void S2C_RES_LOGIN::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& S2C_RES_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:S2C_RES_LOGIN.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void S2C_RES_LOGIN::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:S2C_RES_LOGIN.nickname)
}
void S2C_RES_LOGIN::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:S2C_RES_LOGIN.nickname)
}
void S2C_RES_LOGIN::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:S2C_RES_LOGIN.nickname)
}
::std::string* S2C_RES_LOGIN::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:S2C_RES_LOGIN.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* S2C_RES_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:S2C_RES_LOGIN.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void S2C_RES_LOGIN::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:S2C_RES_LOGIN.nickname)
}

inline const S2C_RES_LOGIN* S2C_RES_LOGIN::internal_default_instance() {
  return &S2C_RES_LOGIN_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
