// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

#ifndef PROTOBUF_Protocols_2eproto__INCLUDED
#define PROTOBUF_Protocols_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_Protocols_2eproto();
void protobuf_InitDefaults_Protocols_2eproto();
void protobuf_AssignDesc_Protocols_2eproto();
void protobuf_ShutdownFile_Protocols_2eproto();

class C2S_REQ_Chat;
class C2S_REQ_LOGIN;
class S2C_RES_LOGIN;

enum packet_number {
  NONE = 0,
  packet_number_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  packet_number_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool packet_number_IsValid(int value);
const packet_number packet_number_MIN = NONE;
const packet_number packet_number_MAX = NONE;
const int packet_number_ARRAYSIZE = packet_number_MAX + 1;

const ::google::protobuf::EnumDescriptor* packet_number_descriptor();
inline const ::std::string& packet_number_Name(packet_number value) {
  return ::google::protobuf::internal::NameOfEnum(
    packet_number_descriptor(), value);
}
inline bool packet_number_Parse(
    const ::std::string& name, packet_number* value) {
  return ::google::protobuf::internal::ParseNamedEnum<packet_number>(
    packet_number_descriptor(), name, value);
}
// ===================================================================

class C2S_REQ_Chat : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:C2S_REQ_Chat) */ {
 public:
  C2S_REQ_Chat();
  virtual ~C2S_REQ_Chat();

  C2S_REQ_Chat(const C2S_REQ_Chat& from);

  inline C2S_REQ_Chat& operator=(const C2S_REQ_Chat& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_REQ_Chat& default_instance();

  static const C2S_REQ_Chat* internal_default_instance();

  void Swap(C2S_REQ_Chat* other);

  // implements Message ----------------------------------------------

  inline C2S_REQ_Chat* New() const { return New(NULL); }

  C2S_REQ_Chat* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2S_REQ_Chat& from);
  void MergeFrom(const C2S_REQ_Chat& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2S_REQ_Chat* other);
  void UnsafeMergeFrom(const C2S_REQ_Chat& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 sender_id = 1;
  void clear_sender_id();
  static const int kSenderIdFieldNumber = 1;
  ::google::protobuf::int32 sender_id() const;
  void set_sender_id(::google::protobuf::int32 value);

  // optional string message = 3;
  void clear_message();
  static const int kMessageFieldNumber = 3;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:C2S_REQ_Chat)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  ::google::protobuf::int32 sender_id_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Protocols_2eproto_impl();
  friend void  protobuf_AddDesc_Protocols_2eproto_impl();
  friend void protobuf_AssignDesc_Protocols_2eproto();
  friend void protobuf_ShutdownFile_Protocols_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<C2S_REQ_Chat> C2S_REQ_Chat_default_instance_;

// -------------------------------------------------------------------

class C2S_REQ_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:C2S_REQ_LOGIN) */ {
 public:
  C2S_REQ_LOGIN();
  virtual ~C2S_REQ_LOGIN();

  C2S_REQ_LOGIN(const C2S_REQ_LOGIN& from);

  inline C2S_REQ_LOGIN& operator=(const C2S_REQ_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_REQ_LOGIN& default_instance();

  static const C2S_REQ_LOGIN* internal_default_instance();

  void Swap(C2S_REQ_LOGIN* other);

  // implements Message ----------------------------------------------

  inline C2S_REQ_LOGIN* New() const { return New(NULL); }

  C2S_REQ_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2S_REQ_LOGIN& from);
  void MergeFrom(const C2S_REQ_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(C2S_REQ_LOGIN* other);
  void UnsafeMergeFrom(const C2S_REQ_LOGIN& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string nickname = 1;
  void clear_nickname();
  static const int kNicknameFieldNumber = 1;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // @@protoc_insertion_point(class_scope:C2S_REQ_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Protocols_2eproto_impl();
  friend void  protobuf_AddDesc_Protocols_2eproto_impl();
  friend void protobuf_AssignDesc_Protocols_2eproto();
  friend void protobuf_ShutdownFile_Protocols_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<C2S_REQ_LOGIN> C2S_REQ_LOGIN_default_instance_;

// -------------------------------------------------------------------

class S2C_RES_LOGIN : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:S2C_RES_LOGIN) */ {
 public:
  S2C_RES_LOGIN();
  virtual ~S2C_RES_LOGIN();

  S2C_RES_LOGIN(const S2C_RES_LOGIN& from);

  inline S2C_RES_LOGIN& operator=(const S2C_RES_LOGIN& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_RES_LOGIN& default_instance();

  static const S2C_RES_LOGIN* internal_default_instance();

  void Swap(S2C_RES_LOGIN* other);

  // implements Message ----------------------------------------------

  inline S2C_RES_LOGIN* New() const { return New(NULL); }

  S2C_RES_LOGIN* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2C_RES_LOGIN& from);
  void MergeFrom(const S2C_RES_LOGIN& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(S2C_RES_LOGIN* other);
  void UnsafeMergeFrom(const S2C_RES_LOGIN& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool is_mine = 1;
  void clear_is_mine();
  static const int kIsMineFieldNumber = 1;
  bool is_mine() const;
  void set_is_mine(bool value);

  // optional string nickname = 2;
  void clear_nickname();
  static const int kNicknameFieldNumber = 2;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // @@protoc_insertion_point(class_scope:S2C_RES_LOGIN)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  bool is_mine_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_Protocols_2eproto_impl();
  friend void  protobuf_AddDesc_Protocols_2eproto_impl();
  friend void protobuf_AssignDesc_Protocols_2eproto();
  friend void protobuf_ShutdownFile_Protocols_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<S2C_RES_LOGIN> S2C_RES_LOGIN_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// C2S_REQ_Chat

// optional int32 sender_id = 1;
inline void C2S_REQ_Chat::clear_sender_id() {
  sender_id_ = 0;
}
inline ::google::protobuf::int32 C2S_REQ_Chat::sender_id() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_Chat.sender_id)
  return sender_id_;
}
inline void C2S_REQ_Chat::set_sender_id(::google::protobuf::int32 value) {
  
  sender_id_ = value;
  // @@protoc_insertion_point(field_set:C2S_REQ_Chat.sender_id)
}

// optional string message = 3;
inline void C2S_REQ_Chat::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& C2S_REQ_Chat::message() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_Chat.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S_REQ_Chat::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:C2S_REQ_Chat.message)
}
inline void C2S_REQ_Chat::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:C2S_REQ_Chat.message)
}
inline void C2S_REQ_Chat::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:C2S_REQ_Chat.message)
}
inline ::std::string* C2S_REQ_Chat::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:C2S_REQ_Chat.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2S_REQ_Chat::release_message() {
  // @@protoc_insertion_point(field_release:C2S_REQ_Chat.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S_REQ_Chat::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:C2S_REQ_Chat.message)
}

inline const C2S_REQ_Chat* C2S_REQ_Chat::internal_default_instance() {
  return &C2S_REQ_Chat_default_instance_.get();
}
// -------------------------------------------------------------------

// C2S_REQ_LOGIN

// optional string nickname = 1;
inline void C2S_REQ_LOGIN::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& C2S_REQ_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:C2S_REQ_LOGIN.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S_REQ_LOGIN::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:C2S_REQ_LOGIN.nickname)
}
inline void C2S_REQ_LOGIN::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:C2S_REQ_LOGIN.nickname)
}
inline void C2S_REQ_LOGIN::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:C2S_REQ_LOGIN.nickname)
}
inline ::std::string* C2S_REQ_LOGIN::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:C2S_REQ_LOGIN.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* C2S_REQ_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:C2S_REQ_LOGIN.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void C2S_REQ_LOGIN::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:C2S_REQ_LOGIN.nickname)
}

inline const C2S_REQ_LOGIN* C2S_REQ_LOGIN::internal_default_instance() {
  return &C2S_REQ_LOGIN_default_instance_.get();
}
// -------------------------------------------------------------------

// S2C_RES_LOGIN

// optional bool is_mine = 1;
inline void S2C_RES_LOGIN::clear_is_mine() {
  is_mine_ = false;
}
inline bool S2C_RES_LOGIN::is_mine() const {
  // @@protoc_insertion_point(field_get:S2C_RES_LOGIN.is_mine)
  return is_mine_;
}
inline void S2C_RES_LOGIN::set_is_mine(bool value) {
  
  is_mine_ = value;
  // @@protoc_insertion_point(field_set:S2C_RES_LOGIN.is_mine)
}

// optional string nickname = 2;
inline void S2C_RES_LOGIN::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& S2C_RES_LOGIN::nickname() const {
  // @@protoc_insertion_point(field_get:S2C_RES_LOGIN.nickname)
  return nickname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2C_RES_LOGIN::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:S2C_RES_LOGIN.nickname)
}
inline void S2C_RES_LOGIN::set_nickname(const char* value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:S2C_RES_LOGIN.nickname)
}
inline void S2C_RES_LOGIN::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:S2C_RES_LOGIN.nickname)
}
inline ::std::string* S2C_RES_LOGIN::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:S2C_RES_LOGIN.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* S2C_RES_LOGIN::release_nickname() {
  // @@protoc_insertion_point(field_release:S2C_RES_LOGIN.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void S2C_RES_LOGIN::set_allocated_nickname(::std::string* nickname) {
  if (nickname != NULL) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:S2C_RES_LOGIN.nickname)
}

inline const S2C_RES_LOGIN* S2C_RES_LOGIN::internal_default_instance() {
  return &S2C_RES_LOGIN_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::packet_number> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::packet_number>() {
  return ::packet_number_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Protocols_2eproto__INCLUDED
