// Auto-generated by enum_mapper_generator.py
// DO NOT EDIT THIS FILE MANUALLY

using System;
using System.Collections.Generic;

public static class PacketNumberMapper
{
    private static readonly Dictionary<string, ushort> NameToNumber = new Dictionary<string, ushort>
    {
        { "TestEcho", 1 },
        { "AccountRegister", 2 },
        { "AccountLogin", 3 },
    };

    private static readonly Dictionary<ushort, string> NumberToName = new Dictionary<ushort, string>
    {
        { 1, "TestEcho" },
        { 2, "AccountRegister" },
        { 3, "AccountLogin" },
    };

    /// <summary>
    /// 메시지 타입명에서 protocol number 추출
    /// 예: "C2S_TestEcho" → 1
    /// </summary>
    public static ushort GetProtocolNumber(string messageTypeName)
    {
        // "_" 뒤의 packet_number 이름 추출
        int pos = messageTypeName.IndexOf('_');
        if (pos == -1)
        {
            throw new ArgumentException($"Invalid message type name: {messageTypeName}");
        }
        
        string packetName = messageTypeName.Substring(pos + 1);
        
        if (NameToNumber.TryGetValue(packetName, out ushort number))
        {
            return number;
        }
        
        throw new ArgumentException($"Unknown packet name: {packetName}");
    }

    /// <summary>
    /// protocol number에서 패킷 이름 추출
    /// </summary>
    public static string GetPacketName(ushort protocolNumber)
    {
        if (NumberToName.TryGetValue(protocolNumber, out string name))
        {
            return name;
        }
        
        return "UNKNOWN";
    }

    /// <summary>
    /// 제네릭 타입에서 protocol number 추출
    /// </summary>
    public static ushort GetProtocolNumber<T>()
    {
        return GetProtocolNumber(typeof(T).Name);
    }
}
