// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocols.proto
// Protobuf C++ Version: 6.33.1

#include "Protocols.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr S2C_RES_LOGIN::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        is_mine_{false} {}

template <typename>
PROTOBUF_CONSTEXPR S2C_RES_LOGIN::S2C_RES_LOGIN(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(S2C_RES_LOGIN_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct S2C_RES_LOGINDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S2C_RES_LOGINDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~S2C_RES_LOGINDefaultTypeInternal() {}
  union {
    S2C_RES_LOGIN _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S2C_RES_LOGINDefaultTypeInternal _S2C_RES_LOGIN_default_instance_;

inline constexpr C2S_REQ_LOGIN::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nickname_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR C2S_REQ_LOGIN::C2S_REQ_LOGIN(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(C2S_REQ_LOGIN_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C2S_REQ_LOGINDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_REQ_LOGINDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_REQ_LOGINDefaultTypeInternal() {}
  union {
    C2S_REQ_LOGIN _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_REQ_LOGINDefaultTypeInternal _C2S_REQ_LOGIN_default_instance_;

inline constexpr C2S_REQ_Chat::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sender_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR C2S_REQ_Chat::C2S_REQ_Chat(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(C2S_REQ_Chat_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct C2S_REQ_ChatDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C2S_REQ_ChatDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~C2S_REQ_ChatDefaultTypeInternal() {}
  union {
    C2S_REQ_Chat _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C2S_REQ_ChatDefaultTypeInternal _C2S_REQ_Chat_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_Protocols_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_Protocols_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocols_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::C2S_REQ_Chat, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::C2S_REQ_Chat, _impl_.sender_id_),
        PROTOBUF_FIELD_OFFSET(::C2S_REQ_Chat, _impl_.message_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::C2S_REQ_LOGIN, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::C2S_REQ_LOGIN, _impl_.nickname_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::S2C_RES_LOGIN, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::S2C_RES_LOGIN, _impl_.is_mine_),
        PROTOBUF_FIELD_OFFSET(::S2C_RES_LOGIN, _impl_.nickname_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::C2S_REQ_Chat)},
        {7, sizeof(::C2S_REQ_LOGIN)},
        {12, sizeof(::S2C_RES_LOGIN)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_C2S_REQ_Chat_default_instance_._instance,
    &::_C2S_REQ_LOGIN_default_instance_._instance,
    &::_S2C_RES_LOGIN_default_instance_._instance,
};
const char descriptor_table_protodef_Protocols_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017Protocols.proto\"2\n\014C2S_REQ_Chat\022\021\n\tsen"
    "der_id\030\001 \001(\005\022\017\n\007message\030\003 \001(\t\"!\n\rC2S_REQ"
    "_LOGIN\022\020\n\010nickname\030\001 \001(\t\"2\n\rS2C_RES_LOGI"
    "N\022\017\n\007is_mine\030\001 \001(\010\022\020\n\010nickname\030\002 \001(\t*\031\n\r"
    "packet_number\022\010\n\004NONE\020\000b\006proto3"
};
static ::absl::once_flag descriptor_table_Protocols_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocols_2eproto = {
    false,
    false,
    191,
    descriptor_table_protodef_Protocols_2eproto,
    "Protocols.proto",
    &descriptor_table_Protocols_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_Protocols_2eproto::offsets,
    file_level_enum_descriptors_Protocols_2eproto,
    file_level_service_descriptors_Protocols_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL packet_number_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Protocols_2eproto);
  return file_level_enum_descriptors_Protocols_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t packet_number_internal_data_[] = {
    65536u, 0u, };
// ===================================================================

class C2S_REQ_Chat::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<C2S_REQ_Chat>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_._has_bits_);
};

C2S_REQ_Chat::C2S_REQ_Chat(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_REQ_Chat_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:C2S_REQ_Chat)
}
PROTOBUF_NDEBUG_INLINE C2S_REQ_Chat::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::C2S_REQ_Chat& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

C2S_REQ_Chat::C2S_REQ_Chat(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const C2S_REQ_Chat& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_REQ_Chat_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  C2S_REQ_Chat* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.sender_id_ = from._impl_.sender_id_;

  // @@protoc_insertion_point(copy_constructor:C2S_REQ_Chat)
}
PROTOBUF_NDEBUG_INLINE C2S_REQ_Chat::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void C2S_REQ_Chat::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sender_id_ = {};
}
C2S_REQ_Chat::~C2S_REQ_Chat() {
  // @@protoc_insertion_point(destructor:C2S_REQ_Chat)
  SharedDtor(*this);
}
inline void C2S_REQ_Chat::SharedDtor(MessageLite& self) {
  C2S_REQ_Chat& this_ = static_cast<C2S_REQ_Chat&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL C2S_REQ_Chat::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) C2S_REQ_Chat(arena);
}
constexpr auto C2S_REQ_Chat::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(C2S_REQ_Chat),
                                            alignof(C2S_REQ_Chat));
}
constexpr auto C2S_REQ_Chat::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_C2S_REQ_Chat_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &C2S_REQ_Chat::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<C2S_REQ_Chat>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &C2S_REQ_Chat::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<C2S_REQ_Chat>(), &C2S_REQ_Chat::ByteSizeLong,
              &C2S_REQ_Chat::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_._cached_size_),
          false,
      },
      &C2S_REQ_Chat::kDescriptorMethods,
      &descriptor_table_Protocols_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull C2S_REQ_Chat_class_data_ =
        C2S_REQ_Chat::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
C2S_REQ_Chat::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&C2S_REQ_Chat_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(C2S_REQ_Chat_class_data_.tc_table);
  return C2S_REQ_Chat_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 2, 0, 28, 2>
C2S_REQ_Chat::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967290,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    C2S_REQ_Chat_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::C2S_REQ_Chat>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 sender_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(C2S_REQ_Chat, _impl_.sender_id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_.sender_id_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 sender_id = 1;
    {PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_.sender_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(C2S_REQ_Chat, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\0\7\0\0\0\0\0"
    "C2S_REQ_Chat"
    "message"
  }},
};
PROTOBUF_NOINLINE void C2S_REQ_Chat::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_REQ_Chat)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.sender_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL C2S_REQ_Chat::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const C2S_REQ_Chat& this_ = static_cast<const C2S_REQ_Chat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL C2S_REQ_Chat::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const C2S_REQ_Chat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:C2S_REQ_Chat)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 sender_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_sender_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_sender_id(), target);
    }
  }

  // string message = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "C2S_REQ_Chat.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:C2S_REQ_Chat)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t C2S_REQ_Chat::ByteSizeLong(const MessageLite& base) {
  const C2S_REQ_Chat& this_ = static_cast<const C2S_REQ_Chat&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t C2S_REQ_Chat::ByteSizeLong() const {
  const C2S_REQ_Chat& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:C2S_REQ_Chat)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string message = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // int32 sender_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_sender_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_sender_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void C2S_REQ_Chat::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<C2S_REQ_Chat*>(&to_msg);
  auto& from = static_cast<const C2S_REQ_Chat&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:C2S_REQ_Chat)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_sender_id() != 0) {
        _this->_impl_.sender_id_ = from._impl_.sender_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void C2S_REQ_Chat::CopyFrom(const C2S_REQ_Chat& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:C2S_REQ_Chat)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C2S_REQ_Chat::InternalSwap(C2S_REQ_Chat* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.sender_id_, other->_impl_.sender_id_);
}

::google::protobuf::Metadata C2S_REQ_Chat::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class C2S_REQ_LOGIN::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<C2S_REQ_LOGIN>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(C2S_REQ_LOGIN, _impl_._has_bits_);
};

C2S_REQ_LOGIN::C2S_REQ_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_REQ_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:C2S_REQ_LOGIN)
}
PROTOBUF_NDEBUG_INLINE C2S_REQ_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::C2S_REQ_LOGIN& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nickname_(arena, from.nickname_) {}

C2S_REQ_LOGIN::C2S_REQ_LOGIN(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const C2S_REQ_LOGIN& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, C2S_REQ_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  C2S_REQ_LOGIN* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:C2S_REQ_LOGIN)
}
PROTOBUF_NDEBUG_INLINE C2S_REQ_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nickname_(arena) {}

inline void C2S_REQ_LOGIN::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
C2S_REQ_LOGIN::~C2S_REQ_LOGIN() {
  // @@protoc_insertion_point(destructor:C2S_REQ_LOGIN)
  SharedDtor(*this);
}
inline void C2S_REQ_LOGIN::SharedDtor(MessageLite& self) {
  C2S_REQ_LOGIN& this_ = static_cast<C2S_REQ_LOGIN&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nickname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL C2S_REQ_LOGIN::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) C2S_REQ_LOGIN(arena);
}
constexpr auto C2S_REQ_LOGIN::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(C2S_REQ_LOGIN),
                                            alignof(C2S_REQ_LOGIN));
}
constexpr auto C2S_REQ_LOGIN::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_C2S_REQ_LOGIN_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &C2S_REQ_LOGIN::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<C2S_REQ_LOGIN>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &C2S_REQ_LOGIN::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<C2S_REQ_LOGIN>(), &C2S_REQ_LOGIN::ByteSizeLong,
              &C2S_REQ_LOGIN::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(C2S_REQ_LOGIN, _impl_._cached_size_),
          false,
      },
      &C2S_REQ_LOGIN::kDescriptorMethods,
      &descriptor_table_Protocols_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull C2S_REQ_LOGIN_class_data_ =
        C2S_REQ_LOGIN::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
C2S_REQ_LOGIN::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&C2S_REQ_LOGIN_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(C2S_REQ_LOGIN_class_data_.tc_table);
  return C2S_REQ_LOGIN_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 30, 2>
C2S_REQ_LOGIN::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(C2S_REQ_LOGIN, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    C2S_REQ_LOGIN_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::C2S_REQ_LOGIN>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nickname = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(C2S_REQ_LOGIN, _impl_.nickname_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string nickname = 1;
    {PROTOBUF_FIELD_OFFSET(C2S_REQ_LOGIN, _impl_.nickname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\10\0\0\0\0\0\0"
    "C2S_REQ_LOGIN"
    "nickname"
  }},
};
PROTOBUF_NOINLINE void C2S_REQ_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:C2S_REQ_LOGIN)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nickname_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL C2S_REQ_LOGIN::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const C2S_REQ_LOGIN& this_ = static_cast<const C2S_REQ_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL C2S_REQ_LOGIN::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const C2S_REQ_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:C2S_REQ_LOGIN)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string nickname = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nickname().empty()) {
      const ::std::string& _s = this_._internal_nickname();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "C2S_REQ_LOGIN.nickname");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:C2S_REQ_LOGIN)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t C2S_REQ_LOGIN::ByteSizeLong(const MessageLite& base) {
  const C2S_REQ_LOGIN& this_ = static_cast<const C2S_REQ_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t C2S_REQ_LOGIN::ByteSizeLong() const {
  const C2S_REQ_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:C2S_REQ_LOGIN)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // string nickname = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nickname().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_nickname());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void C2S_REQ_LOGIN::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<C2S_REQ_LOGIN*>(&to_msg);
  auto& from = static_cast<const C2S_REQ_LOGIN&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:C2S_REQ_LOGIN)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_nickname().empty()) {
      _this->_internal_set_nickname(from._internal_nickname());
    } else {
      if (_this->_impl_.nickname_.IsDefault()) {
        _this->_internal_set_nickname("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void C2S_REQ_LOGIN::CopyFrom(const C2S_REQ_LOGIN& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:C2S_REQ_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void C2S_REQ_LOGIN::InternalSwap(C2S_REQ_LOGIN* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
}

::google::protobuf::Metadata C2S_REQ_LOGIN::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class S2C_RES_LOGIN::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<S2C_RES_LOGIN>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_._has_bits_);
};

S2C_RES_LOGIN::S2C_RES_LOGIN(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_RES_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:S2C_RES_LOGIN)
}
PROTOBUF_NDEBUG_INLINE S2C_RES_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::S2C_RES_LOGIN& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nickname_(arena, from.nickname_) {}

S2C_RES_LOGIN::S2C_RES_LOGIN(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const S2C_RES_LOGIN& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, S2C_RES_LOGIN_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  S2C_RES_LOGIN* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.is_mine_ = from._impl_.is_mine_;

  // @@protoc_insertion_point(copy_constructor:S2C_RES_LOGIN)
}
PROTOBUF_NDEBUG_INLINE S2C_RES_LOGIN::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nickname_(arena) {}

inline void S2C_RES_LOGIN::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.is_mine_ = {};
}
S2C_RES_LOGIN::~S2C_RES_LOGIN() {
  // @@protoc_insertion_point(destructor:S2C_RES_LOGIN)
  SharedDtor(*this);
}
inline void S2C_RES_LOGIN::SharedDtor(MessageLite& self) {
  S2C_RES_LOGIN& this_ = static_cast<S2C_RES_LOGIN&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.nickname_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL S2C_RES_LOGIN::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) S2C_RES_LOGIN(arena);
}
constexpr auto S2C_RES_LOGIN::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(S2C_RES_LOGIN),
                                            alignof(S2C_RES_LOGIN));
}
constexpr auto S2C_RES_LOGIN::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_S2C_RES_LOGIN_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &S2C_RES_LOGIN::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<S2C_RES_LOGIN>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &S2C_RES_LOGIN::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<S2C_RES_LOGIN>(), &S2C_RES_LOGIN::ByteSizeLong,
              &S2C_RES_LOGIN::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_._cached_size_),
          false,
      },
      &S2C_RES_LOGIN::kDescriptorMethods,
      &descriptor_table_Protocols_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull S2C_RES_LOGIN_class_data_ =
        S2C_RES_LOGIN::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
S2C_RES_LOGIN::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&S2C_RES_LOGIN_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(S2C_RES_LOGIN_class_data_.tc_table);
  return S2C_RES_LOGIN_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2>
S2C_RES_LOGIN::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    S2C_RES_LOGIN_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::S2C_RES_LOGIN>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string nickname = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_.nickname_)}},
    // bool is_mine = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(S2C_RES_LOGIN, _impl_.is_mine_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_.is_mine_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_mine = 1;
    {PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_.is_mine_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string nickname = 2;
    {PROTOBUF_FIELD_OFFSET(S2C_RES_LOGIN, _impl_.nickname_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\10\0\0\0\0\0"
    "S2C_RES_LOGIN"
    "nickname"
  }},
};
PROTOBUF_NOINLINE void S2C_RES_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:S2C_RES_LOGIN)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nickname_.ClearNonDefaultToEmpty();
  }
  _impl_.is_mine_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL S2C_RES_LOGIN::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const S2C_RES_LOGIN& this_ = static_cast<const S2C_RES_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL S2C_RES_LOGIN::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const S2C_RES_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:S2C_RES_LOGIN)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool is_mine = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_is_mine() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_is_mine(), target);
    }
  }

  // string nickname = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_nickname().empty()) {
      const ::std::string& _s = this_._internal_nickname();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "S2C_RES_LOGIN.nickname");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:S2C_RES_LOGIN)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t S2C_RES_LOGIN::ByteSizeLong(const MessageLite& base) {
  const S2C_RES_LOGIN& this_ = static_cast<const S2C_RES_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t S2C_RES_LOGIN::ByteSizeLong() const {
  const S2C_RES_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:S2C_RES_LOGIN)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // string nickname = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_nickname().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_nickname());
      }
    }
    // bool is_mine = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_is_mine() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void S2C_RES_LOGIN::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<S2C_RES_LOGIN*>(&to_msg);
  auto& from = static_cast<const S2C_RES_LOGIN&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:S2C_RES_LOGIN)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_nickname().empty()) {
        _this->_internal_set_nickname(from._internal_nickname());
      } else {
        if (_this->_impl_.nickname_.IsDefault()) {
          _this->_internal_set_nickname("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_is_mine() != 0) {
        _this->_impl_.is_mine_ = from._impl_.is_mine_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void S2C_RES_LOGIN::CopyFrom(const S2C_RES_LOGIN& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:S2C_RES_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void S2C_RES_LOGIN::InternalSwap(S2C_RES_LOGIN* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.nickname_, &other->_impl_.nickname_, arena);
  swap(_impl_.is_mine_, other->_impl_.is_mine_);
}

::google::protobuf::Metadata S2C_RES_LOGIN::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_Protocols_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
